name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest upstream release
        uses: actions/github-script@v7
        id: 'latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const releases = await github.rest.repos.getLatestRelease({
              owner: 'caddyserver',
              repo: 'caddy',
            });
            return releases.data.tag_name.replace('v', '');
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/caddy
          flavor: |
            latest=${{ github.ref_name == 'main' }}
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.latest.outputs.result }}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          build-args: |
            "VERSION=${{ steps.latest.outputs.result }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
