name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest upstream release
        uses: actions/github-script@v5
        id: 'latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const releases = await github.rest.repos.getLatestRelease({
              owner: 'caddyserver',
              repo: 'caddy',
            });
            return releases.data.tag_name.replace('v', '');
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/caddy
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.latest.outputs.result }}
            type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "VERSION=${{ steps.latest.outputs.result }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
